Repository hassio-addons/addon-mopidy, pull requests merged in 2021-01, with the labels that each got.

#83 Allow dependabot to upgrade Python dependencies
  .github/dependabot.yaml
Labels: ci

#87 Remove webui configuration, as Ingress is enabled on this add-on
  mopidy/config.json
Labels: refactor

#86 Upgrade add-on base image to 4.1.0
  mopidy/Dockerfile
  mopidy/build.json
Labels: dependencies

#88 Refactor NGINX configuration and HA authentication
  mopidy/Dockerfile
  mopidy/config.json
  mopidy/rootfs/etc/cont-init.d/11-nginx.sh
  mopidy/rootfs/etc/cont-init.d/nginx.sh
  mopidy/rootfs/etc/nginx/ha-auth.lua
  mopidy/rootfs/etc/nginx/includes/resolver.conf
  mopidy/rootfs/etc/nginx/lua/ha-auth.lua
  mopidy/rootfs/etc/nginx/modules/ndk_http.conf
  mopidy/rootfs/etc/nginx/modules/ngx_http_lua.conf
  mopidy/rootfs/etc/nginx/nginx.conf
  mopidy/rootfs/etc/nginx/servers/.gitkeep
  mopidy/rootfs/etc/nginx/servers/direct-ssl.disabled
  mopidy/rootfs/etc/nginx/servers/direct.disabled
  mopidy/rootfs/etc/nginx/templates/direct.gtpl
  mopidy/rootfs/etc/nginx/templates/ingress.gtpl
  mopidy/rootfs/etc/services.d/nginx/run
Labels: refactor

#89 Restructure init scripts
  mopidy/rootfs/etc/cont-init.d/81-python-packages.sh
  mopidy/rootfs/etc/cont-init.d/folders.sh
  mopidy/rootfs/etc/cont-init.d/packages.sh
Labels: refactor

#91 Fixes Ingress acesss
  mopidy/rootfs/etc/cont-init.d/nginx.sh
Labels: bugfix
